spring.application.name=api-eventostec

spring.datasource.url=jdbc:postgresql://localhost:5432/eventostec
spring.datasource.username=user-eventostec
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

aws.region=us-east-1
aws.access-key-id=test
aws.secret-access-key=test
aws.s3.endpoint=http://localhost:4566
aws.s3.bucket=eventostec-images
